FROM node:18.18.0 as builder

WORKDIR /usr/src/app

COPY ./package*.json .

RUN npm install --save-dev vite

COPY . .

RUN npm run build

FROM node:18.18.0-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist /usr/src/app/dist
COPY --from=builder /usr/src/app/package.json /usr/src/app/package.json

RUN npm install 
# --production

EXPOSE 4173

CMD [ "npm", "run", "preview" ]
