version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"

  database:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - ./database/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/data:/data/db
      - ./database/data/log:/var/log/mongodb
    ports:
      - "27017:27017"

  dbclient:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    depends_on:
      - database
    ports:
      - "8081:8081"
